name = "ai-qa-worker"  # Your worker name (change if needed)
main = "worker.js"  # Entry-point script
compatibility_date = "2024-02-05"
account_id = "your-cloudflare-account-id"  # Replace with your actual Cloudflare Account ID
workers_dev = true
