name = "aipoweredqaplatform"  # Change this to your worker name
main = "worker.js"  # Specify the entry point script
compatibility_date = "2024-02-07"

account_id = "your-cloudflare-account-id"  # Replace with your actual Cloudflare Account ID
workers_dev = true

[vars]
OPENAI_API_KEY = "your-secret-api-key"  # Store your OpenAI API key securely

[build]
command = "npm install && npm run build"
